import { useState, useMemo } from "react";
import { format } from "date-fns";
import { findFibonnaci } from "./fibonacci";
import useTime from "./useTime";
function Example1Usememo() {
  console.log("component rendering");

  const [selectedNumber, setSelectedNumber] = useState(5);
  const time = useTime();
  // * -------------------------------------------
  // const fibNums = [];
  // for (let i = 1; i <= selectedNumber; i++) {
  // console.log("calculating fibs");

  //   fibNums.push(findFibonnaci(i));
  // }
  // * -------------------------------------------

  const fibNums = useMemo(() => {
    const result = [];

    for (let i = 1; i <= selectedNumber; i++) {
      console.log("calculating fibs");
      result.push(findFibonnaci(i));
    }

    return result;
  }, [selectedNumber]);
  return (
    <div>
      {/* {JSON.stringify(time)} */}
      <h2>Time : {format(time, "hh:mm:ss a")}</h2>
      <br />
      <input
        type="number"
        name="number"
        id="number"
        value={selectedNumber}
        onChange={(e) => {
          setSelectedNumber(e.target.value);
        }}
      />
      {selectedNumber > 0 && (
        <div>
          <h2>First {selectedNumber} fibonacci numbers are </h2>
          {fibNums.join(", ")}
        </div>
      )}
    </div>
  );
}

export default Example1Usememo;

/*
! useMemo() hook syntax...

useMemo(()=>{
  
  }, [])

it has a callback and a dependency array... and this callback runs only when the value of the dependency changes...
* and we must return a value from the callback...

*/

/*

what i need to do here is ---> find fibonacchi No. between 1-16

whatever code we written here in this component, we can't really change it and make it more optimized...


*/

// ! whenever you do any expensive computation then you should use useMemo() hook...

// * ##############################################################################################################

/*

# Understanding this React `useMemo` example

This component is designed to demonstrate a problem: React is doing an expensive Fibonacci calculation again and again, even when the calculation's input hasn't changed.

The purpose of `useMemo()` is to avoid repeating that calculation unnecessarily.

Let's understand exactly what's happening, why it happens, and how `useMemo()` solves it.

## 1. What is this component trying to do?

Your component has two responsibilities:

1. Let the user select a number between 1 and 16.

2. Display the first `selectedNumber` Fibonacci numbers.

For example, if the user enters `5`, the component displays:

Selected number

5

## First 5 Fibonacci numbers are

1, 1, 2, 3, 5

The Fibonacci sequence is generated by a function such as:

JavaScript

```
function findFibonnaci(n) {
  if (n <= 2) return 1;

  return findFibonnaci(n - 1) + findFibonnaci(n - 2);
}
```

This is a recursive implementation. For larger values, it performs a lot of repeated work, which makes it a useful example for demonstrating memoization.

## 2. Understand the imports

JavaScript

```
import { useState } from "react";

import { findFibonnaci } from "./fibonacci";

import useTime from "./useTime";
```

There are three things being imported:

`useState`

React's hook for storing state. Here, it stores the number selected by the user.

`findFibonnaci`

A function imported from another file. It calculates a Fibonacci number.

`useTime`

A custom hook. It presumably gives the component the current time and updates it periodically.

The important point is that `useTime()` can cause this component to render repeatedly, even when `selectedNumber` stays the same.

## 3. What happens when the component first renders?

Look at this code:

JavaScript

```
function Example1Usememo() {
  const [selectedNumber, setSelectedNumber] = useState(1);

  const time = useTime();

  const fibNums = [];

  for (let i = 1; i <= selectedNumber; i++) {
    fibNums.push(findFibonnaci(i));
  }

  // JSX returned here
}
```

Let's follow the execution in order.

### Step 1: React calls the component function

React executes:

JavaScript

```
Example1Usememo();
```

The function starts running from the top to the bottom.

### Step 2: React initializes the state

JavaScript

```
const [selectedNumber, setSelectedNumber] = useState(1);
```

The initial selected number is `1`.

Conceptually, React stores something like:

```
React's state:
selectedNumber = 1
```

The two variables mean:

* `selectedNumber`: The current value of the state.

* `setSelectedNumber`: A function that asks React to update that state.

### Step 3: The custom time hook runs

JavaScript

```
const time = useTime();
```

Suppose the current time is:

```
07:16:00
```

The hook returns that time.

If `useTime()` uses an interval to update the time every second, it will eventually ask React to render the component again.

### Step 4: The Fibonacci array is created

JavaScript

```
const fibNums = [];
```

A new empty array is created during this execution of the component.

```
fibNums = []
```

### Step 5: The `for` loop executes

JavaScript

```
for (let i = 1; i <= selectedNumber; i++) {
  fibNums.push(findFibonnaci(i));
}
```

Since `selectedNumber` is `1`, the loop runs once.

```
i = 1
1 <= 1  → true

findFibonnaci(1) → 1

fibNums.push(1)
```

Now:

```
fibNums = [1]
```

### Step 6: React receives the JSX

The component returns the UI:

JavaScript

```
<div>
  {JSON.stringify(time)}
  <br />

  <input
    type="number"
    value={selectedNumber}
    onChange={(e) => {
      setSelectedNumber(e.target.value);
    }}
  />

  {selectedNumber > 0 && (
    <div>
      <h2>First {selectedNumber} fibonacci numbers are</h2>
      {fibNums.join(", ")}
    </div>
  )}
</div>
```

React uses this returned JSX to update the browser's displayed UI.

At this point, the user sees the time, an input containing `1`, and the first Fibonacci number.


## 4. The important part: Why does the Fibonacci calculation run again?

This is the central concept you need to understand.

Imagine that `useTime()` updates the time every second.

The component might render like this:

## Render timeline

1. Initial render

   `selectedNumber = 5`

   The loop calculates Fibonacci numbers from 1 to 5.

2. One second later

   `useTime()` updates the time.

   React renders the component again.

3. Second render

   `selectedNumber` is still `5`.

   But the `for` loop runs again and calculates Fibonacci numbers from 1 to 5 again.

4. Another second later

   The time changes again.

   React renders again, and the Fibonacci calculation repeats again.

The crucial rule is:

> When a React component renders, the component function executes again from the beginning.

React does not automatically remember that a particular calculation was already performed just because its result was the same.

### Visualizing the repeated work

Suppose `selectedNumber = 5`.

Without memoization:

```
Initial render
│
├── findFibonnaci(1)
├── findFibonnaci(2)
├── findFibonnaci(3)
├── findFibonnaci(4)
└── findFibonnaci(5)

Time updates
│
└── React renders again
    │
    ├── findFibonnaci(1)
    ├── findFibonnaci(2)
    ├── findFibonnaci(3)
    ├── findFibonnaci(4)
    └── findFibonnaci(5)

Time updates again
│
└── React renders again
    │
    ├── findFibonnaci(1)
    ├── findFibonnaci(2)
    ├── findFibonnaci(3)
    ├── findFibonnaci(4)
    └── findFibonnaci(5)
```

The selected number has not changed, but the calculations are repeated.

This is what your comment is trying to demonstrate:

JavaScript

```
// console.log("calculating fibs");
```

If you uncomment that line, you can observe how often the loop executes.

## 5. Why does React render again when the time changes?

Think of React state as a trigger.

```
State changes
     │
     ▼
React schedules a render
     │
     ▼
Component function executes
     │
     ▼
All ordinary JavaScript inside it runs
     │
     ▼
React updates the UI where necessary
```

Your component depends on two pieces of changing information:

JavaScript

```
const [selectedNumber, setSelectedNumber] = useState(1);

const time = useTime();
```

Changing `selectedNumber` causes a render.

Changing the state inside `useTime()` also causes a render.

React doesn't look at the body of your function and decide:

> "The time changed, but the Fibonacci code is unrelated, so I'll skip it."

Instead, the function runs again. Ordinary JavaScript statements execute again unless you explicitly arrange for a result to be reused.

Important distinction: React may avoid changing a particular DOM element if its output is unchanged. But that does not mean the JavaScript calculation that produced the output was skipped.

## 6. What exactly is the problem with this loop?

Your original code:

JavaScript

```
const fibNums = [];

for (let i = 1; i <= selectedNumber; i++) {
  fibNums.push(findFibonnaci(i));
}
```

There are two separate things happening:

### A. Creating the array

JavaScript

```
const fibNums = [];
```

This creates a new array every time the component function executes.

### B. Performing the expensive calculation

JavaScript

```
findFibonnaci(i);
```

This calculates a Fibonacci number.

The second part is the expensive work we want to avoid repeating.

For example, if the selected number is `16`, the loop calls:

```
findFibonnaci(1)
findFibonnaci(2)
findFibonnaci(3)
...
findFibonnaci(16)
```

If `findFibonnaci()` uses naive recursion, the calculation for larger numbers involves many repeated recursive calls.

The issue is not that React is necessarily slow at rendering. The issue is that you are asking JavaScript to perform the same expensive calculation again during every render.

# 7. What is `useMemo()`?

`useMemo()` is a React hook that lets you cache the result of a calculation between renders.

The basic structure is:

JavaScript

```
const result = useMemo(() => {
  // Expensive calculation
  return someValue;
}, [dependencies]);
```

It has two parts:

###

1. Calculation function

JavaScript

```
() => {
  return someValue;
}
```

This tells React how to calculate the value.

###

2. Dependency array

JavaScript

```
[dependencies]
```

This tells React which values the calculation depends on.

The mental model is:

> "React, calculate this value when necessary. If the dependencies have not changed, give me the previously calculated result instead of running the calculation again."

It is a performance optimization, not a way to make the calculation itself mathematically faster.

## 8. Applying `useMemo()` to your exact example

First, import the hook:

JavaScript

```
import { useMemo, useState } from "react";
```

Then replace the ordinary Fibonacci calculation with:

JavaScript

```
const fibNums = useMemo(() => {
  const nums = [];

  for (let i = 1; i <= selectedNumber; i++) {
    console.log("calculating fibs");
    nums.push(findFibonnaci(i));
  }

  return nums;
}, [selectedNumber]);
```

Notice what changed:

* The calculation was moved inside the function passed to `useMemo()`.

* The dependency array is `[selectedNumber]`.

* The calculated array is returned from the function.

* React gives you the cached result when `selectedNumber` has not changed.

The rest of your component can remain essentially the same.

## 9. How the new version behaves

Let's assume the user selects `5`.

## Try the memoization idea

Illustrative

Change the selected number or simulate a time update. The calculation runs only when the selected number changes.

Selected number

7

Simulated time updates

0

Update timeReset

What happens?

Memoized result

Initial render: calculate the first 7 Fibonacci numbers.

The interactive example illustrates the dependency rule; it does not execute your actual React component.

### Case A: The time changes

```
selectedNumber = 5
time = 07:16:00
```

React renders and `useMemo()` calculates:

```
[1, 1, 2, 3, 5]
```

Now the time changes:

```
selectedNumber = 5
time = 07:16:01
```

React renders again.

`useMemo()` compares the dependency:

```
Previous selectedNumber = 5
Current selectedNumber  = 5

Are they different? No.
```

Therefore, React can return the previously stored array instead of executing the Fibonacci calculation again.

### Case B: The user changes the number

The user changes the input from `5` to `6`.

```
Previous selectedNumber = 5
Current selectedNumber  = 6

Are they different? Yes.
```

Now the calculation runs again:

```
findFibonnaci(1)
findFibonnaci(2)
...
findFibonnaci(6)
```

The new result is cached:

```
[1, 1, 2, 3, 5, 8]
```

The next time the clock updates, React can reuse this new result.

## 10. What does the dependency array really mean?

This is the most important `useMemo()` rule.

JavaScript

```
useMemo(() => {
  // Calculation
}, [selectedNumber]);
```

It means:

> "This calculation depends on `selectedNumber`. Recalculate it when that dependency changes."

It does not mean:

> "Run this calculation only once."

Compare these examples:

|
Code

|

Meaning

|
| --- | --- |
|

`useMemo(() => value, [])`

|

Cache based on no changing dependencies; normally calculate on the initial mount.

|
|

`useMemo(() => value, [selectedNumber])`

|

Recalculate when `selectedNumber` changes.

|
|

`useMemo(() => value, [selectedNumber, time])`

|

Recalculate when either dependency changes.

|

For your case, the Fibonacci array depends on `selectedNumber`, but it does not depend on `time`.

Therefore:

JavaScript

```
[selectedNumber]
```

is the appropriate dependency array.

# 11. What is actually stored in memory?

Suppose this code runs:

JavaScript

```
const fibNums = useMemo(() => {
  const nums = [];

  for (let i = 1; i <= selectedNumber; i++) {
    nums.push(findFibonnaci(i));
  }

  return nums;
}, [selectedNumber]);
```

On the initial render, React conceptually stores something like:

```
React's memoized value

Dependencies:
[selectedNumber = 5]

Cached result:
[1, 1, 2, 3, 5]
```

On the next render, React checks the dependency array.

```
Previous dependencies:
[5]

Current dependencies:
[5]
```

Since the dependency has not changed, React returns the cached result.

When the selected number changes to `6`:

```
Previous dependencies:
[5]

Current dependencies:
[6]
```

The dependency changed, so React executes the calculation and replaces the cached result.

```
New dependencies:
[6]

New cached result:
[1, 1, 2, 3, 5, 8]
```

This is the core mechanism behind memoization.

## 12. Why can't React automatically do this for every calculation?

This is a very good question. Why doesn't React inspect your code and automatically know that the Fibonacci calculation can be reused?

There are several reasons.

### Reason 1: React doesn't know which calculations are expensive

Consider:

JavaScript

```
const result = a + b;
```

And:

JavaScript

```
const result = findFibonnaci(16);
```

Both are ordinary JavaScript expressions. React doesn't know whether a function is cheap, expensive, or has side effects simply by looking at the component's output.

Automatically caching every calculation could introduce unnecessary memory use and bookkeeping.

### Reason 2: JavaScript functions can have side effects

Consider:

JavaScript

```
function getData() {
  console.log("Fetching data");
  return Math.random();
}
```

If React automatically cached every function result, calling this function again might not produce the expected behavior.

For example:

JavaScript

```
getData(); // 0.42
getData(); // 0.91
```

Caching the result would change what the program does.

React cannot assume that every calculation is a pure function whose result can safely be reused.

### Reason 3: Dependency tracking is not always obvious

Consider:

JavaScript

```
const result = expensiveCalculation(user, settings, items);
```

The result might depend on the contents of `user`, `settings`, and `items`, or on values hidden inside nested objects.

React would need to understand those dependencies and know when their relevant values changed. That is not generally possible through simple inspection of arbitrary JavaScript.

### Reason 4: The developer chooses the performance trade-off

Caching has a cost too.

You need to:

* Store the previous result.

* Store the dependencies.

* Compare dependencies on later renders.

* Keep the cached value in memory.

For a cheap calculation, the cost of caching might be greater than the cost of recalculating.

That is why `useMemo()` is an explicit optimization rather than something you should apply blindly to every expression.

# 13. An important correction to the comment in your notes

You wrote:

JavaScript

```
// ! whenever you do any expensive computation then you should use useMemo() hook...
```

That is a useful beginner's rule, but it is too absolute.

A better rule is:

> Use `useMemo()` when a calculation is expensive enough that avoiding repeated work matters, and when its inputs remain unchanged across renders often enough for caching to provide a benefit.

For your example, the Fibonacci calculation is a reasonable candidate because:

* `useTime()` causes frequent renders.

* The selected number may remain unchanged across those renders.

* Fibonacci calculation can become expensive with naive recursion.

* The calculation is pure: the same input produces the same output.

However, there is another important point.

## 14. `useMemo()` is not the same as making Fibonacci faster

Your current Fibonacci function may be inefficient because it repeatedly calculates the same subproblems.

For example:

```
findFibonnaci(5)
│
├── findFibonnaci(4)
│   ├── findFibonnaci(3)
│   └── findFibonnaci(2)
│
└── findFibonnaci(3)
    ├── findFibonnaci(2)
    └── findFibonnaci(1)
```

The value of `findFibonnaci(3)` is calculated more than once.

There are two different optimization problems:

React-level memoization

`useMemo()` prevents the whole Fibonacci array calculation from running on renders where `selectedNumber` hasn't changed.

Algorithm-level optimization

Improve `findFibonnaci()` itself, for example with dynamic programming or an iterative approach, so each Fibonacci number is calculated more efficiently.

`useMemo()` does not automatically fix the inefficient recursion inside `findFibonnaci()`.

## 15. One more detail: Your input value is a string

Your code contains:

JavaScript

```
<input
  type="number"
  value={selectedNumber}
  onChange={(e) => {
    setSelectedNumber(e.target.value);
  }}
/>
```

Even though the HTML input has `type="number"`, `e.target.value` is a string.

So after the user types `5`, the state may become:

JavaScript

```
selectedNumber = "5";
```

The loop still generally works because JavaScript converts the string to a number when comparing:

JavaScript

```
i <= selectedNumber
```

But for cleaner state management, you could convert it explicitly:

JavaScript

```
onChange={(e) => {
  setSelectedNumber(Number(e.target.value));
}}
```

This is separate from `useMemo()`, but it is an important detail to understand in this component.

# Final mental model

Remember this sequence whenever you see a React component with an expensive calculation:

## The pattern to recognize

Component renders

Expensive calculation runs

Result is displayed

Unrelated state changes

Component renders again

Without useMemo()

Expensive calculation repeats.

With useMemo(\(selectedNumber\))

Reuse the previous result if `selectedNumber` hasn't changed.

The key question to ask yourself is:

"Does this component render again while the inputs to this expensive calculation remain the same?"

If the answer is yes, `useMemo()` may be useful.


*/

/*

* the selectedNumber starts with 5, so at initial render it will calculate from 1-5. and then again it will calculate freshly , doing this expensive work repeatedly ...now if i do 6 by increasing the number input tag, now after every render it will calculate from 1-6....like it's calculating then erasing it's result in the next mount and then again calculating for the same range !!!.... now if i use useMemo() hook, then at initial render 1-5 will happen, then if i do it 6, then cache result of 1-5 & new 6th fibonacci number will be added depending on the cache result right ??? and if the selectedNumber does not change then it will show the cache result again and again right ??? and useMemo is using DP memoization trick right ?
==>
Gourab, your understanding is mostly correct, but there are two important details to fix:

1. `useMemo()` does cache the result when `selectedNumber` stays the same.

2. `useMemo()` does not automatically calculate only the new 6th Fibonacci number using the cached result of 1–5. That is a separate optimization.

Let's break it down.

## 1. Your understanding of ordinary rendering is correct

Suppose the initial state is:

JavaScript

```
const [selectedNumber, setSelectedNumber] = useState(5);
```

On the initial render:

```
selectedNumber = 5

fibNums = []

i = 1 → calculate fib(1)
i = 2 → calculate fib(2)
i = 3 → calculate fib(3)
i = 4 → calculate fib(4)
i = 5 → calculate fib(5)

fibNums = [1, 1, 2, 3, 5]
```

Now the user increases the input to `6`.

JavaScript

```
setSelectedNumber(6);
```

React renders the component again.

Your ordinary code runs again:

JavaScript

```
const fibNums = [];

for (let i = 1; i <= selectedNumber; i++) {
  fibNums.push(findFibonnaci(i));
}
```

This produces:

```
New render
│
├── Create a new empty fibNums array
│
├── Calculate fib(1)
├── Calculate fib(2)
├── Calculate fib(3)
├── Calculate fib(4)
├── Calculate fib(5)
└── Calculate fib(6)
```

The previous array `[1, 1, 2, 3, 5]` is not automatically reused by this code.

So yes, your understanding of the repeated calculation is correct.

One small terminology correction: this is a new render, not necessarily a new mount. A mount is when the component is first inserted into the UI. Updating state normally causes a re-render, not a remount.

## 2. What happens when you use `useMemo()`?

Suppose you write:

JavaScript

```
const fibNums = useMemo(() => {
  const nums = [];

  for (let i = 1; i <= selectedNumber; i++) {
    nums.push(findFibonnaci(i));
  }

  return nums;
}, [selectedNumber]);
```

Now let's trace the behavior.

## Render 1: selectedNumber = 5

Dependency

5

Calculation runs

`findFibonnaci(1)` through `findFibonnaci(5)`

Cached result

\(1, 1, 2, 3, 5\)

User changes 5 → 6

## Render 2: selectedNumber = 6

Dependency

6

Calculation runs again

`findFibonnaci(1)` through `findFibonnaci(6)`

New cached result

\(1, 1, 2, 3, 5, 8\)

Important: In this code, when `selectedNumber` changes from `5` to `6`, React calls the entire calculation function again.

It does not automatically say:

> "I already know the first five numbers. I'll just calculate the sixth one."

So the result is cached between renders, but the calculation itself still starts at `1` whenever the dependency changes.

## 3. What happens if `selectedNumber` stays at 6?

Now imagine `useTime()` updates the time every second.

```
Initial:
selectedNumber = 6
time = 07:16:00
```

`useMemo()` calculates the array and stores the result.

Then:

```
Time changes:
selectedNumber = 6
time = 07:16:01
```

React renders again.

`useMemo()` checks:

```
Previous dependency: 6
Current dependency:  6

Changed? No.
```

It returns the cached array:

```
[1, 1, 2, 3, 5, 8]
```

The Fibonacci calculation function does not need to execute again.

So your statement here is correct:

> If `selectedNumber` does not change, `useMemo()` can return the cached result again and again across re-renders.

# 4. Is `useMemo()` using the DP memoization trick?

Conceptually, yes: both use the idea of memoization. But React's `useMemo()` and dynamic programming are not the same thing.

The shared idea is:

> Store a previously calculated result and reuse it instead of doing the same work again.

However, they operate at different levels.

## React `useMemo()`

Caches the result of a calculation across component renders.

JavaScript

```
const result = useMemo(() => {
  return expensiveCalculation(selectedNumber);
}, [selectedNumber]);
```

Its question is:

> "Do I need to run this whole calculation again during this render?"

## Dynamic programming

Stores results of smaller subproblems so that a larger problem can reuse them.

JavaScript

```
dp[0] = 0;
dp[1] = 1;

for (let i = 2; i <= n; i++) {
  dp[i] = dp[i - 1] + dp[i - 2];
}
```

Its question is:

> "Have I already solved this smaller part of the problem?"

Both use stored results, but the scope of the cache is different.

## 5. The exact difference using Fibonacci

### A. `useMemo()` caches the entire array

Your React code:

JavaScript

```
const fibNums = useMemo(() => {
  const nums = [];

  for (let i = 1; i <= selectedNumber; i++) {
    nums.push(findFibonnaci(i));
  }

  return nums;
}, [selectedNumber]);
```

Think of it as:

```
selectedNumber = 5

Cache:
Input: 5
Output: [1, 1, 2, 3, 5]
```

When the input becomes `6`, the cached result for input `5` is not automatically extended. The calculation runs again for the new input.

### B. DP caches individual Fibonacci subproblems

A dynamic programming approach might store:

```
dp[1] = 1
dp[2] = 1
dp[3] = 2
dp[4] = 3
dp[5] = 5
```

Then, to calculate the sixth number:

```
dp[6] = dp[5] + dp[4]
      = 5 + 3
      = 8
```

Here, the previous results for `dp[4]` and `dp[5]` are reused directly.

That is closer to what you described when you said:

> "The cache result of 1–5 will be kept, and the new 6th Fibonacci number will be added."

That behavior is incremental dynamic programming, not something that ordinary `useMemo()` automatically provides.

## 6. A useful way to remember the difference

## Two different caches

`useMemo()`

Cache the result of the entire calculation for a given dependency value.

React render optimization

DP

Cache smaller subproblem results so larger calculations can reuse them.

Algorithm optimization

One final nuance: React's `useMemo()` is a performance optimization, not a permanent storage guarantee. React may discard a memoized value in certain situations, so your code must still be correct if the calculation runs again.

The most accurate conclusion is:

Your understanding of `useMemo()` preventing repeated Fibonacci calculations when `selectedNumber` stays unchanged is correct. Your idea of reusing 1–5 and calculating only 6 is the DP-style optimization, which `useMemo()` alone does not automatically perform.

*/

/*
* Okay. Okay. So now I understand that what is the deal here? That we are, by useMemo, by using useMemo, we are basically deciding when to, whether to call the expensive function or not. Like whether to, you know, whether to run the Fibonacci, find Fibonacci code or not. Whether to run the loop or not. That's what we are doing by useMemo.
==>
Exactly, Gourab. You've understood the main idea.

With `useMemo()`, you're telling React:

> "This calculation is expensive. Before running it again, check whether its dependencies have changed. If they haven't changed, reuse the previous result instead of running the calculation."

In your example:

JavaScript

```
const fibNums = useMemo(() => {
  const nums = [];

  for (let i = 1; i <= selectedNumber; i++) {
    nums.push(findFibonnaci(i));
  }

  return nums;
}, [selectedNumber]);
```

The dependency is `selectedNumber`.

* If `selectedNumber` stays the same, React can reuse the cached `fibNums`. The loop and Fibonacci calls don't run again.

* If `selectedNumber` changes, React runs the calculation again, including the loop and all its Fibonacci calls.

One small wording correction: you're not directly deciding whether to call `findFibonnaci()` yourself. You're giving React a calculation and its dependencies, allowing React to decide whether to reuse the previous result or execute the calculation.

Your mental model is now correct: `useMemo()` helps prevent unnecessary execution of an expensive calculation during re-renders.



*/
