import { configureStore } from "@reduxjs/toolkit";
import counterReducer from "../features/counter/counterSlice";

export const store = configureStore({
  reducer: {
    counter: counterReducer,
  },
});

/*

whole application's state will be here inside of store...
and we have to use the state everywhere...

*/

// inside of store we write reducers...

// i have told earlier, in our application there can be many features...
// i can think of that, we have one feature which is counter...
// and for features we use slices...

// if we have to change the state, for that we use dispatch() function...
// and inside of that dispatch function, we tell what is the action going to be...
// dispatch function as a input takes action.

// but we can have multiple features so for that we gonna create slice...
// and in every slice we gonna write it's reducers...
// inside of reducer it consists of logic which changes the state...

// every feature you made, you have to tell here in the store,
// that it's been added...
